name: Pull request Deploy preview

on:
  pull_request_target:
    types:
      - opened
      - reopened
      - synchronize

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: peter-evans/create-or-update-comment@v2
        id: comment
        name: Create initial comment
        with:
          body: |-
            ## Deploy Preview
            
            | Name   | Link           |
            | ------ | -------------- |
            | Status | Building...    |
            | Commit | ${GITHUB_SHA}  |
          issue-number: ${{ github.event.pull_request.number }}
          token: ${{ secrets.BOT }}
      - uses: actions/checkout@v3
        name: Checkout Code
        with:
          ref: refs/pull/${{ github.event.pull_request.number }}/merge
      - uses: actions/setup-python@v3
        name: Setup Python
        with:
          python-version: 3.7
      - name: Install depencencies
        run: |
          python -m pip install --upgrade pip setuptools
          python -m pip install -r requirements.txt
      - name: Build docs
        run: mkdocs build
      - uses: peaceiris/actions-gh-pages@v3
        name: Deploy pages
        with:
          personal_token: ${{ secrets.BOT }}
          publish_dir: ./site
          destination_dir: ./${{ github.repository }}/${{ github.event.pull_request.number }}
          external_repository: gh-pages-deploy/Deploy-Previews
      - name: Delay comment update by 1 minute
        run: sleep 1m
        shell: bash
      - uses: peter-evans/create-or-update-comment@v2
        name: Update comment.
        with:
          body: |-
            ## Deploy Preview
            
            | Name   | Link                                                                                               |
            | ------ | -------------------------------------------------------------------------------------------------- |
            | Status | Ready!                                                                                             |
            | Commit | ${GITHUB_SHA}                                                                                      |
            | Link   | https://gh-pages-deploy.github.io/${{ github.repository }}/${{ github.event.pull_request.number }} |
            | Logs   | ${{ github.server_url }}/${{ github.repository }}/actions/run/${{ github.run_id }}                 |
          comment-id: ${{ steps.comment.outputs.comment-id }}
          edit-mode: replace
          token: ${{ secrets.BOT }}
      - if: ${{ failure() }}
        uses: peter-evans/create-or-update-comment@v2
        name: Update comment.
        with:
          body: |-
            ## Deploy Preview
            
            | Name   | Link                                                                                               |
            | ------ | -------------------------------------------------------------------------------------------------- |
            | Status | Deployment failed!                                                                                 |
            | Commit | ${GITHUB_SHA}                                                                                      |
            | Logs   | ${{ github.server_url }}/${{ github.repository }}/actions/run/${{ github.run_id }}                 |
          comment-id: ${{ steps.comment.outputs.comment-id }}
          edit-mode: replace
          token: ${{ secrets.BOT }}
