name: Pull request Deploy preview

on:
  pull_request_target:
    types:
      - opened
      - reopened
      - synchronize
    paths:
      - '.github/**'
      - '!.snippets/**'
      - '!docs/**'
      - '!theme/**'
      - '!mkdocs.yml'
      - 'requirements.txt'

jobs:
  deploy-preview:
    runs-on: ubuntu-latest
    steps:
      - run: 'echo "Skipping Deploy Preview"'
